# Generated by Django 4.1.3 on 2022-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.PositiveIntegerField(choices=[(3, 'Lakes'), (2, 'Mountains'), (1, 'See')]),
        ),
    ]
