# Generated by Django 4.1.3 on 2022-11-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Cottage', 'Cottage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Sea', 'Sea'), ('Lakes', 'Lakes')], max_length=20),
        ),
    ]
