# Generated by Django 4.1.3 on 2022-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='image',
        ),
        migrations.AddField(
            model_name='places',
            name='images',
            field=models.ImageField(default='', upload_to='places_img'),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Cottage', 'Cottage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Mountains', 'Mountains'), ('Lakes', 'Lakes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placesimage',
            name='images',
            field=models.ImageField(upload_to='places_img'),
        ),
    ]
