# Generated by Django 4.0.1 on 2022-11-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_alter_places_object_type_alter_places_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel')], max_length=20),
        ),
    ]
