# Generated by Django 4.1.3 on 2022-11-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_alter_places_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.PositiveIntegerField(choices=[(2, 'Apartment'), (1, 'Hotel'), (3, 'Cottage')]),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.PositiveIntegerField(choices=[(1, 'See'), (2, 'Mountains'), (3, 'Lakes')]),
        ),
    ]
