# Generated by Django 4.1.3 on 2022-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_alter_places_object_type_alter_places_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Hotel', 'Hotel'), ('Apartment', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Lakes', 'Lakes'), ('Sea', 'Sea')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlaceFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=100)),
                ('all_facilities', models.ManyToManyField(to='places_app.places')),
            ],
        ),
    ]
