# Generated by Django 4.1.3 on 2022-12-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_alter_places_object_type_alter_places_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Mountains', 'Mountains'), ('Lakes', 'Lakes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placesimage',
            name='images',
            field=models.ImageField(upload_to='places_img'),
        ),
    ]
