# Generated by Django 4.0.1 on 2022-11-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0003_alter_places_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Cottage', 'Cottage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Mountains', 'Mountains'), ('Lakes', 'Lakes')], max_length=20),
        ),
    ]
