# Generated by Django 4.1.3 on 2022-11-21 17:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0003_alter_places_object_type_alter_places_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placefacilities',
            name='all_facilities',
        ),
        migrations.RemoveField(
            model_name='placefacilities',
            name='facilities',
        ),
        migrations.AddField(
            model_name='placefacilities',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Lakes', 'Lakes'), ('Sea', 'Sea'), ('Mountains', 'Mountains')], max_length=20),
        ),
    ]
