# Generated by Django 4.0.1 on 2022-11-25 17:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0004_alter_places_object_type_alter_places_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Swimming pool'), (2, 'Free parking outside'), (3, 'Wi-Fi'), (4, 'Pet friendly'), (5, 'SPA'), (6, 'Private kitchen'), (7, 'Bike rating'), (8, 'BBQ Place'), (9, 'coffee maker'), (10, 'family room')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Cottage', 'Cottage'), ('Apartment', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('50.00'))]),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Lakes', 'Lakes'), ('Mountains', 'Mountains'), ('Sea', 'Sea')], max_length=20),
        ),
    ]
