# Generated by Django 4.1.3 on 2022-12-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0004_remove_places_image_places_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='images',
        ),
        migrations.AddField(
            model_name='places',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Hotel', 'Hotel'), ('Apartment', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Lakes', 'Lakes'), ('Sea', 'Sea')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placesimage',
            name='images',
            field=models.FileField(upload_to='places_img'),
        ),
    ]
