# Generated by Django 4.0.1 on 2022-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0004_alter_places_object_type_alter_places_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Mountains', 'Mountains'), ('Lakes', 'Lakes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placesimage',
            name='images',
            field=models.ImageField(upload_to='places_img'),
        ),
    ]
