# Generated by Django 4.1.3 on 2022-11-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0005_alter_places_object_type_alter_places_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='placefacilities',
            name='all_facilities',
            field=models.ManyToManyField(to='places_app.places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Mountains', 'Mountains'), ('Lakes', 'Lakes')], max_length=20),
        ),
    ]
