# Generated by Django 4.1.3 on 2022-11-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0007_alter_placefacilities_my_field2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='facilities',
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Lakes', 'Lakes'), ('Sea', 'Sea')], max_length=20),
        ),
    ]
