# Generated by Django 4.0.1 on 2022-11-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0008_alter_places_object_type_alter_places_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='images',
            field=models.ImageField(upload_to='explore_media/places_img'),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Cottage', 'Cottage'), ('Hotel', 'Hotel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Sea', 'Sea'), ('Lakes', 'Lakes')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlacesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='places_img')),
                ('places', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places_app.places')),
            ],
        ),
    ]
