# Generated by Django 4.1.3 on 2022-11-21 18:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0009_places_facilities_alter_placefacilities_my_field2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placefacilities',
            name='my_field2',
        ),
        migrations.AlterField(
            model_name='places',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Swimming pool'), (2, 'Free parking outside')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Lakes', 'Lakes'), ('Sea', 'Sea')], max_length=20),
        ),
    ]
