# Generated by Django 4.1.3 on 2022-11-21 18:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0010_remove_placefacilities_my_field2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Swimming pool'), (2, 'Free parking outside'), (3, 'Wi-Fi'), (4, 'Pet friendly'), (5, 'SPA'), (6, 'Private kitchen'), (7, 'Bike rating'), (8, 'BBQ Place'), (9, 'coffee maker'), (10, 'family room')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Cottage', 'Cottage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Lakes', 'Lakes'), ('Mountains', 'Mountains')], max_length=20),
        ),
    ]
