# Generated by Django 4.1.3 on 2022-11-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0014_alter_places_facilities_alter_places_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='object_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Cottage', 'Cottage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Lakes', 'Lakes'), ('Sea', 'Sea')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PlaceFacilities',
        ),
    ]
