# Generated by Django 4.1.3 on 2022-11-23 21:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0015_alter_places_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='places',
            name='region',
            field=models.CharField(choices=[('Lakes', 'Lakes'), ('Sea', 'Sea'), ('Mountains', 'Mountains')], max_length=20),
        ),
    ]
