# Generated by Django 4.1.3 on 2022-12-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0003_alter_places_object_type_alter_places_region'),
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='places_app.places'),
        ),
    ]
