# Generated by Django 4.1.3 on 2022-11-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_auto_20221113_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
